### ISSUE TITLE
Where is the best place to report issues?

### ISSUE THREAD

**Issue by andymac4182** [mohachouch/forms-wpf-progress#6]
Hi, I am attempting to use the nightly and was wondering where you would like the issues reported.

System.NullReferenceException: 'Object reference not set to an instance of an object.'

![image](https://user-images.githubusercontent.com/1297073/34654230-ab741260-f444-11e7-9023-e7c2479a0341.png)

   at Xamarin.Forms.Forms.Init() in D:\agent\_work\6\s\Xamarin.Forms.Platform.WPF\Forms.cs:line 26
   at ImpulseOSD.UI.WPF.MainWindow..ctor() in C:\dev\Git\ImpulseRC\ImpulseOSD\ImpulseOSD.UI.WPF\MainWindow.xaml.cs:line 13

**Comment by andymac4182** [comment]
If I manually pulled in the Forms class this is where I got an error

![image](https://user-images.githubusercontent.com/1297073/34654851-f292a276-f44c-11e7-9c24-0e37d5a36322.png)

**Comment by andymac4182** [comment]
Sorry I missed the changes to `App.xaml`
https://github.com/xamarin/Xamarin.Forms/blob/4f3d347b3e58c9a0ad0f75e7e924dafe7e04fc00/Xamarin.Forms.ControlGallery.WPF/App.xaml

**Comment by mohachouch** [comment]
Hi,

On the latest version, the dictionary is automatically added.

You can directly use the report of bug of the official repository of Xamarin.

Thanks
